apiVersion: v2
name: app-mendix
version: 2.2.2
description: Mendix Application Chart.
icon: https://cinaq.github.io/helm-charts/icons/mendix-logo.png
maintainers:
- email: x@cinaq.com
  name: Xiwen Cheng
- email: viktor@cinaq.com
  name: Viktor Berlov
