apiVersion: v2
name: app-mendix
version: 2.1.0
description: Mendix Application Chart.
icon: https://cinaq.github.io/helm-charts/icons/mendix-logo.png
maintainers:
- email: x@cinaq.com
  name: Xiwen Cheng
